info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java:
      version: @java.version@

spring:
  application:
    name: @project.name@

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://root:password@localhost:27017/desafio-tecnico-amcom?authSource=admin}
      auto-index-creation: true
  kafka:
    consumer:
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      batch-size: 65536
    listener:
      ack-mode: manual_immediate
    bootstrap-servers: ${BOOTSTRAP_SERVERS:PLAINTEXT://localhost:9092}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    operations-sorter: alpha
    filter: true
    configUrl: /v3/api-docs/swagger-config
    disable-swagger-default-url: true
    url: /v3/api-docs
    enabled: true
    path: swagger-ui.html
    tagsSorter: alpha
    defaultModelsExpandDepth: -1
    docExpansion: list
    syntax-highlight:
      activated: true